stateDiagram-v2
    [*] --> Initialization

    state Initialization {
        AssingPiority: Assign priority according to the algorithm policy.
        ResetSystem: Reset global state.
        ReleaseFirstJobs: Release the first jobs for each task.
        AssingPiority --> ResetSystem
        ResetSystem --> ReleaseFirstJobs
    }

    state "Event Loop" as EventLoop {

        CheckNextEventTime : Check if we are still within the simulation duration.
        state NextEventTimeCheck <<choice>>
        AvailableTime: Calculate available time from now to next event.
        DistributeTime: Distribute available time among ready tasks.
        AdvaceTime : Advance time to the next event.
        CheckDeadline : Check deadline miss.
        state DeadlineCheck <<choice>>
        ReleaseJob : Release new job for the task has completed their periods.

        [*] --> TakeNextEvent
        TakeNextEvent --> CheckNextEventTime
        CheckNextEventTime --> NextEventTimeCheck
        NextEventTimeCheck --> [*] : Simulation Ended
        NextEventTimeCheck --> AvailableTime : Continue
        AvailableTime --> DistributeTime
        DistributeTime --> AdvaceTime
        AdvaceTime --> CheckDeadline
        CheckDeadline --> DeadlineCheck
        DeadlineCheck --> ReleaseJob : State Ok
        ReleaseJob --> TakeNextEvent
    }

    Initialization --> EventLoop
    DeadlineCheck --> [*] : Deadline Missed
    EventLoop --> [*]
