classDiagram
    class Scheduler {
        <<abstract>>
        -taskSet: TaskSet
        +analyze() void
        #assignPriority() void
    }

    class DMScheduler {
        #assignPriority() void
    }

    class TaskSet {
        -tasks: Set~Task~
    }

    class Task {
        -period: Duration
        -deadline: Duration
        -executionTimeSampler: Sampler
        -priority: int
        +releaseJob(Duration releaseTime) Job
    }

    class Job {
        -task: Task
        -releaseTime: Duration
        -absoluteDeadline: Duration
        -remainingExecutionTime: Duration
        -isCompleted: boolean
        +execute(Duration availableTime) Duration
    }

    class MyClock {
        -currentTime: Duration
        +reset() MyClock
        +getCurrentTime() Duration
        +advanceTo(Duration newTime) void
        +advanceBy(Duration delta) void
    }

    %% Relations
    Scheduler --> TaskSet
    Scheduler o-- Job : readyJobs
    TaskSet *-- Task
    Task -- Job
    Job --> Task
    Scheduler <|-- DMScheduler