classDiagram

    %% Scheduler
    class Scheduler {
        <<abstract>>
        - taskSet : TaskSet
        - clock : MyClock
        - simulationDuration : Duration
        - logger : TraceLogger
        + analyze() : void
    }

    class FixedPriorityScheduler {
        <<abstract>>
        + analyze() : void
        # assignPriority() : void
    }

    class DMScheduler {
        <<final>>
        # assignPriority() : void
    }

    %% TaskSet
    class TaskSet {
        <<final>>
        - tasks : Set~Task~
    }

    class Task {
        <<final>>
        - periodSampler : Sampler
        - deadline : Duration
        - executionTimeSampler : Sampler
        - priority : int
        + sampleNextPeriod() : Duration
        + releaseJob(Duration releaseTime) : Job
    }

    class Job {
        <<final>>
        - task : Task
        - absoluteDeadline : Duration
        + execute(Duration durationAvailable) : Duration
        + isDeadlineMissed(Duration currentTime) : boolean
    }

    %% Event
    class Event {
        <<abstract>>
        - time : Duration
    }

    class ReleaseEvent {
        <<final>>
        - task : Task
    }

    class DeadlineEvent {
        <<final>>
        -job : Job
    }

    %% Logger
    class MyLogger {
        <<interface>>
        + log(String message) : void
        + close() : void
    }

    class TraceLogger {
        <<final>>
        + log(String message) : void
        + close() : void
    }

    class NoLogger {
        <<final>>
        + log(String message) : void
        + close() : void
    }

    %% Utils
    class MyClock {
        <<final>>
        - currentTime : Duration
        + advanceTo(Duration newTime) : void
        + advanceBy(Duration delta) : void
        + printCurrentTime() : String
        + reset() : void
    }

    class Sampler {
        <<interface>>
        +getSample() : BigDecimal
    }

    class ConstantSampler {
        <<final>>
        - value : BigDecimal
        + getSample() : BigDecimal
    }

    %% Relationships
    Client --> Scheduler : analyse()
    %% Scheduler
    Scheduler <|-- FixedPriorityScheduler
    FixedPriorityScheduler <|-- DMScheduler
    Scheduler --> MyClock
    Scheduler --> MyLogger
    FixedPriorityScheduler o-- TaskSet
    FixedPriorityScheduler o-- Event : eventQueue
    Scheduler ..> DeadlineMissedException : throws
    %% TaskSet
    TaskSet *-- Task
    Job o-- Task
    Task o-- Sampler : periodSampler
    Task o-- Sampler : executionTimeSampler
    Task ..> Job : releaseJob
    %% Event
    Event <|-- ReleaseEvent
    Event <|-- DeadlineEvent
    %% Logger
    MyLogger <|.. TraceLogger
    MyLogger <|.. NoLogger

    %% Utils
    Sampler <|.. ConstantSampler