@startuml sequence diagram

participant Client
participant Scheduler
participant Job
participant Task
participant MyClock

Client -> Scheduler : schedule
Scheduler -> Scheduler : reset
Scheduler -> MyClock : reset
Scheduler -> Scheduler : initStructures
Scheduler -> Task : releaseJob
Task -> Job : new Job
Scheduler -> Scheduler : releaseAllTasks

loop there is event
Scheduler -> Scheduler : executeFor
Scheduler -> Job : execute
Scheduler -> MyClock : advanceBy
Scheduler -> Scheduler : releasePeriodTasks
Scheduler -> Task : releaseJob
Task -> Job : new Job
end

Scheduler --> Client : trace.log

@enduml
