
classDiagram

    class Bernstein {
        <<static>>
    }

    %% Domain classes
    class BernsteinPolynomial {
        <<final>>
        - double[] functionSampler
        - BernsteinBasis basis
        + eval(double x) double
    }

    class BernsteinBasis {
        <<abstract>>
        + eval(int degree, int i, double x) double
        # abstract map(double x) double
    }

    class ClassicalBernsteinBasis {
        <<final>>
        # map(double x) double
    }

    class LinearBernsteinBasis {
        <<final>>
        - double supportMin
        - double supportMax
        # map(double x) double
    }

    class ExponentialBernsteinBasis {
        <<final>>
        # map(double x) double
    }

    %% Relations
    BernsteinPolynomial o-- BernsteinBasis
    BernsteinBasis <|-- ClassicalBernsteinBasis
    BernsteinBasis <|-- LinearBernsteinBasis
    BernsteinBasis <|-- ExponentialBernsteinBasis
    Bernstein ..> BernsteinPolynomial
