classDiagram

    %% BernsteinFromECDF
    class BernsteinFromECDF {
        <<static-final>>
        + approximateECDFWithNormalBase(ecdf, x, degree)
        + approximateECDFWithLinearBase(ecdf, degree, x, lowerSupport, upperSupport)
        + approximateECDFWithExponentialBase(ecdf, x, degree)
        + approximateEPDFWithNormalBase(ecdf, x, degree)
        + approximateEPDFWithLinearBase(ecdf, x, degree, lowerSupport upperSupport)
        + approximateEPDFWithExponentialBase(ecdf, x, degree)
    }

    class ECDF {
        <<final>>
        data : double[]
        + eval(double x)
    }

    BernsteinFromECDF --> ECDF

    %% BernsteinFromMonomial
    class BernsteinFromMonomial {
        <<static-final>>
    }

    class Polynomial {
        <<abstract>>
        - coefficient : double[]
        + eval(double x)
    }

    class MonomialPolynomial {
        <<final>>
    }

    class BernsteinPolynomial {
        <<final>>
        - basis : Basis
    }

    class BernsteinBasis {
        <<interface>>
    }

    class LinearBernsteinBasis {
        <<final>>
        - lowerSupport : double
        - upperSupport : double
    }

    BernsteinFromMonomial --> Polynomial
    Polynomial <|-- MonomialPolynomial
    Polynomial <|-- BernsteinPolynomial
    BernsteinPolynomial *-- BernsteinBasis
    BernsteinBasis <-- LinearBernsteinBasis